// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cljbwjglmvdpusmfyslh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNsamJ3amdsbXZkcHVzbWZ5c2xoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2OTYzNDUsImV4cCI6MjA2NjI3MjM0NX0.c3cvSuuwe6tUvx6ogBuMHygKRa0wq9wHWjyi8KtotmI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);